- 2016-03-09-qubes-os-3-1-has-been-released.md
Should link to upgrading instructions.
example user confusion:
https://forums.whonix.org/t/whonix-update-failure-recieved-http-code-403-from-proxy-after-connect/2413/17?u=patrick
> fix upgrading confusion

- 2016-09-29-qubes-32.md
"management engine software" is very weird/confusing description for Salt, given previous posts re: ME.
> improve language

- 2019-05-30-fedora-30-template-available.md
Closes QubesOS/qubes-issues#4845
CC: @fepitre
> Announcement: Fedora 30 template available

- 2019-07-09-qubes-4-0-2-rc1.md
Requested by: https://github.com/QubesOS/qubes-issues/issues/5108
> Qubes OS 4.0.2-rc1 announcement

- 2020-11-01-qubes-4-0-4-rc1.md
Announcement for the Qubes OS 4.0.4-rc1 release (QubesOS/qubes-issues#6170).
> Release: Qubes OS 4.0.4-rc1

- 2021-01-22-qubes-4-0-4-rc2.md
Requested by: QubesOS/qubes-issues#6170
> Release: Qubes OS 4.0.4-rc2

- 2021-02-25-fedora-33-templates-available.md
https://github.com/QubesOS/qubes-issues/issues/6039
CC: @fepitre
> Announcement: Fedora 33 templates available

- 2021-03-05-qubes-4-0-4.md
> Release: Qubes OS 4.0.4

- 2021-09-29-whonix-16-template-available.md
Closes QubesOS/qubes-issues#6891
@adrelanos, please review.
> Announcement: Whonix 16 template available

- 2021-11-11-fedora-33-approaching-eol-fedora-34-templates-available.md
Closes QubesOS/qubes-issues#6568
> Announcement: Fedora 33 approaching EOL; Fedora 34 templates available

- 2021-11-11-new-appmenu.md
- 2021-11-12-new-qubes-application-menu.md
Tiny and brief introduction to new qubes app menu
> Article about new menu

- 2022-06-27-qubes-4-1-1-rc1.md
QubesOS/qubes-issues#7544
https://github.com/QubesOS/qubesos.github.io/pull/200
> Release: Qubes OS 4.1.1-rc1

- 2022-06-27-fedora-36-templates-available.md
Closes QubesOS/qubes-issues#7342
> Announcement: Fedora 36 templates available

- 2022-08-07-qubes-os-summit-history.md
Signed-off-by: Michał Żygowski <michal.zygowski@3mdeb.com>
> Qubes OS Summit: History from organizer's perspective

- 2022-09-29-qubes-os-project-now-accepting-donations-on-ethereum.md
Other related PRs:
https://github.com/QubesOS/qubes-secpack/pull/57 (update qubes-secpack file)
https://github.com/QubesOS/qubesos.github.io/pull/205 (add to donations page)
> Announcement: Now accepting donations on Ethereum

- 2023-01-31-trenchboot-aem-for-qubes-os.md
Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>
> 2023-01-31-trenchboot-aem-for-qubes-os.md: synd updated content

- 2023-02-09-qubes-4-1-2-rc1.md
> Release: Qubes OS 4.1.2-rc1

- 2023-03-03-fedora-37-templates-available.md
> Announcement: Fedora 37 templates available

- 2023-03-03-qubes-4-1-2-rc2.md
- 2023-03-06-qubes-4-1-2-rc2.md
> Release: Qubes OS 4.1.2-rc2

- 2023-03-15-qubes-4-1-2.md
Closes QubesOS/qubes-issues#7983
> Release: Qubes OS 4.1.2

- 2019-07-18-insurgo-privacybeast-qubes-certification.md
- 2019-09-18-qubes-presentations-at-platform-security-summit-2019.md
- 2020-03-04-nitropad-x230-qubes-certification.md
- 2021-06-01-nitropad-t430-qubes-certification.md
Merge with: https://github.com/QubesOS/qubes-doc/pull/1298
> Update anchor links for QubesOS/qubes-doc#1298

- 2023-08-XX-debian-12-templates-available.md
Closes QubesOS/qubes-issues#7134
> Announcement: Debian 12 templates available
